name: Build and Publish REST API Docker image

on:
  push:
    branches: [ "dev" ]

env:
  DOCKER_IMAGE_NAME: remote-job-runner-api
  ECR_REPO: eggnog-docker
  AWS_REGION: us-west-2

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo 
      uses: actions/checkout@v4

    - name: Create JSON manifest
      run: |
           echo '{
             "redis_host": "${{ secrets.REDIS_SERVER_HOST}}",
             "redis_port": ${{ vars.REDIS_PORT}},
             "redis_db": ${{secrets.REDIS_DB}},
             "redis_password": ${{secrets.REDIS_SERVER_PASSWORD}}
           }' > config.json
      working-directory: ./api
      shell: bash
    
    #- name: Print Manifest
      #run: cat config.json
      #working-directory: ./api
      #shell: bash